[constants]
root = '/opt/msvc'


[binaries]
# NOTE: `-Xmicrosoft-windows-sys-root` is a thing if i would want to use base clang, but clang-cl is easier to setup
# winsysroot for the compiler requires the value as a seperate arg
cpp = ['clang-cl', '-fuse-ld=lld', '--target=i686-pc-windows-msvc', '/winsysroot', root]
# winsysroot for the linker requires the value after the `:` character...
cpp_ld = ['lld-link', '/winsysroot:' + root]
# llvm rc/windres doesn't support /winsysroot...... so add it with preprocessor-args instead of adding a bunch of manual includes
windres = ['llvm-windres', '--target=i686-pc-windows-msvc', '--preprocessor-arg=-Xmicrosoft-windows-sys-root', '--preprocessor-arg=' + root]
strip = 'llvm-strip'


[host_machine]
system = 'windows'
cpu_family = 'x86'
cpu = 'i686'
endian = 'little'