package fusion:sdk;



world wasm-ext {
    // 32bit pointer, list<u8> doesnt work
    type extension = u32;
    type editdata = list<u8>;

    // stub
    type create-object-info = u32;

    // js classes that will be used in c++ land to get ace params
    resource condition-or-action-manager {
        get-float: func(
            index: s32
        ) -> f32;

        get-string: func(
            index: s32
        ) -> string;

        get-integer: func(
            index: s32
        ) -> s32;

        get-object: func(
            index: s32
        ) -> u32;
    }

    resource expression-manager {
        set-integer: func(
            val: s32
        );

        set-float: func(
            val: f32
        );

        set-string: func(
            str: string
        );


        get-float: func(
            index: s32
        ) -> f32;

        get-string: func(
            index: s32
        ) -> string;

        get-integer: func(
            index: s32
        ) -> s32;

        get-object: func(
            index: s32
        ) -> u32;
    }

    // c++ land exports
    export init:                        func();
    export dealloc:                     func();
    export get-number-of-conditions:    func() -> u32;
    export create-run-object:           func(ed: editdata, cob: create-object-info, version: u32) -> extension;
    export destroy-run-object:          func(cpp-ext: extension, fast: bool);
    export handle-run-object:           func(cpp-ext: extension) -> s16;
    export display-run-object:          func(cpp-ext: extension) -> s16;
    export pause-run-object:            func(cpp-ext: extension) -> s16;
    export continue-run-object:         func(cpp-ext: extension) -> s16;
    export condition-jump:              func(cpp-ext: extension, id: s32, manager: condition-or-action-manager) -> s32;
    export action-jump:                 func(cpp-ext: extension, id: s32, manager: condition-or-action-manager);
    export expression-jump:             func(cpp-ext: extension, id: s32, manager: expression-manager);
}
