name: Update help file

on: gollum
   
# fp-utils-3.2.2 fpc-source-3.2.2 libcmark-gfm-extensions0.29.0.gfm.3 libcmark-gfm0.29.0.gfm.3 pandoc pandoc-data


jobs:
  help:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout master
      uses: actions/checkout@v3
      with:
        path: 'NoiseExtension'

    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: 'kapigames/NoiseExtension.wiki'
        path: 'NoiseExtension.wiki'

    - uses: awalsh128/cache-apt-pkgs-action@v1
      with:
        packages: fp-utils-3.2.2 pandoc pandoc-data libcmark-gfm0.29.0.gfm.3 libcmark-gfm-extensions0.29.0.gfm.3
        version: 1.0

    - name: Run compile script
      run: |
        cd NoiseExtension.wiki
        chmod +x ./compile.sh
        ./compile.sh
        cd ..
        mkdir -p NoiseExtension/Help
        mv NoiseExtension.wiki/temp/Noise.chm NoiseExtension/Help/
    
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      if: github.event_name != 'release'
      with:
        name: Noise help file
        path: ./NoiseExtension/Help/Noise.chm
    
    - name: Commit files
      working-directory: NoiseExtension
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add Help/Noise.chm
        git commit -m "Update help file." -a
    
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        directory: NoiseExtension
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
