name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true

    #- name: Restore NuGet packages
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: nuget restore .

    - name: Build Android ARM
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:"Noise_Android" -p:Configuration="Runtime" -p:Platform="ARM" ./Noise.sln
    
    - name: Build Android ARM64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:"Noise_Android" -p:Configuration="Runtime" -p:Platform="ARM64" ./Noise.sln

    - name: Build Android x86
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:"Noise_Android" -p:Configuration="Runtime" -p:Platform="x86" ./Noise.sln

    - name: Build Android x64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:"Noise_Android" -p:Configuration="Runtime" -p:Platform="x64" ./Noise.sln

    - name: Build Runtime Unicode
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:"Noise_Windows" -p:Configuration="Runtime Unicode" -p:Platform="x86" ./Noise.sln

    - name: Build Edittime Unicode
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild -t:"Noise_Windows" -p:Configuration="Edittime Unicode" -p:Platform="x86" ./Noise.sln


    - uses: actions/upload-artifact@v2
      with:
        name: Noise
        path: ./MFX/