name: Build

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./build.bat --bundle --sdkconfig

    - uses: actions/upload-artifact@v2
      with:
        name: Noise
        path: ./Noise.zip