name: Create offline wiki

on:
  gollum:
  workflow_dispatch:


# Cancel already running ci on a new push
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  Wiki:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main repo
      uses: actions/checkout@v4
      with:
        path: 'NoiseExtension'

    - name: Checkout wiki repo
      uses: actions/checkout@v4
      with:
        repository: 'kapi1525/NoiseExtension.wiki'
        path: 'NoiseExtension.wiki'

    - name: Download ghwiki2chm
      id: download
      uses: robinraju/release-downloader@v1
      with:
        repository: 'kapi1525/ghwiki2chm'
        latest: true
        fileName: '*-x86_64-linux.tar.gz'

    - name: Install ghwiki2chm
      run: |
        tar -xzf "${{ fromJson(steps.download.outputs.downloaded_files)[0] }}"
        sudo cp -rf ghwiki2chm/* /usr/local
        rm -r ghwiki2chm "${{ fromJson(steps.download.outputs.downloaded_files)[0] }}"
        ghwiki2chm -v

    - name: Install chmcmd
      run: sudo apt-get install fp-utils -y

    - name: Run ghwiki2chm
      run: |
        ghwiki2chm -v
        ghwiki2chm -n Noise -r NoiseExtension.wiki -o Noise.chm

    - name: Copy Noise.chm
      run: |
        mkdir -p ./NoiseExtension/Help
        cp Noise.chm ./NoiseExtension/Help

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Noise.chm
        path: Noise.chm

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        path: ./NoiseExtension
        commit-message: Update offline wiki.
        author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
        branch: offline-wiki
        title: Update offline wiki.
        body: Automated pr with updated chm file.


