name: Build and Publish

on:
  release:
    types:
      - published

jobs:
  Build:
    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true

    #- name: Restore NuGet packages
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: nuget restore .

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./build.bat --release --full --noinstall --noclean --bundle
    
    - name: Upload assets to GitHub
      uses: AButler/upload-release-assets@v2.0
      with:
        files: 'Noise.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}