name: Check spelling in wiki

on: gollum


jobs:
  spelling:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout wiki
      uses: actions/checkout@v3
      with:
        repository: 'kapigames/NoiseExtension.wiki'

    - uses: check-spelling/check-spelling@main
      id: spelling
      if: ${{ github.event_name != 'issue_comment' ||
        (
          contains(github.event.comment.body, '@check-spelling-bot apply')
        ) }}
      with:
        experimental_apply_changes_via_bot: 1
